spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    mvc:
       view:
         prefix: /view/
mybatis:
  mapper-locations:
  - classpath:com/example/batch/dao/mapper/*.xml
  type-aliases-package: com.example.batch.entity

